name: Curl Api

on:
  schedule:
    - cron: "*/10 0-14 * * *"
  push:
    branches: main

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run
        run: |
          curl https://star-api.xhemj.now.sh/api/?from=github_action_auto_curl
          curl https://ss.now.sh/github_action_auto_curl?from=github_action_auto_curl
          curl https://ip.xhemj.now.sh/api/ip?from=github_action_auto_curl
