name: Get Mingyan Ranking Data

on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: main

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run
        run: |
          curl https://star-api.xhemj.vercel.app/api/star?token=${{ secrets.RANKING_API_KEY }} > ./data/ranking.json
