name: Get Mingyan Ranking Data

on:
  schedule:
    - cron: "0 0,6,12 * * *"
  push:
    branches: main

jobs:
  get-ranking:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run
        run: |
          curl https://api.erss.club/api/v2/star?token=${{ secrets.RANKING_API_KEY }} > ranking.json

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.1
        with:
            add: ". --force"
            author_name: xhemj-bot
            author_email: xhemj_service@126.com
            message: ":+1: Get Mingyan Ranking Data"
