name: Get Mingyan Ranking Data

on:
  schedule:
    - cron: "0 0,12 * * *"
  push:
    branches: main

jobs:
  get-ranking:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run
        run: |
          curl https://star-api.xhemj.vercel.app/api/star?token=${{ secrets.RANKING_API_KEY }} > ranking.json
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.1
        with:
            add: .
            message: ":+1: Get Mingyan Ranking Data"